version: "3.8"

services:
  minio:
    image: docker.io/minio/minio:latest
    command: ["server", "/data", "--address", ":10000", "--console-address", ":10001"]
    environment:
      MINIO_ROOT_USER: tstdl-dev
      MINIO_ROOT_PASSWORD: tstdl-dev
    volumes:
      - minio-data:/data
    ports:
      - "10000:10000"
      - "10001:10001"

volumes:
  minio-data:
