version: "3.8"

services:
  postgres:
    image: docker.io/postgres:17-alpine
    command: -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: wf7rq6glrk5jykne
    volumes:
      - ./container/postgres/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./container/postgres/init:/docker-entrypoint-initdb.d
      - ./.volumes/postgres-data:/home/postgres/pgdata/data
    ports:
      - 5432:5432

  minio:
    image: docker.io/minio/minio:latest
    command: ["server", "/data", "--address", ":9000", "--console-address", ":9001"]
    environment:
      MINIO_ROOT_USER: tstdl-dev
      MINIO_ROOT_PASSWORD: tstdl-dev
    volumes:
      - ./.volumes/minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
